### ISSUE TITLE
TypeError: this._opts.getModulesRunBeforeMainModule is not a function

### ISSUE THREAD

**Issue by krishnalelas** [facebook/metro#101]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Packager throws the following error when bundling:
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: this._opts.getModulesRunBeforeMainModule is not a function

**Repro Steps**
1. Add metro-bundler 0.22.1 to package.json as a "resolutions" entry for react-native:
```
"resolutions": {
  "react-native/metro-bundler": "0.22.1"
}
```
2. Run react-native run-android as normal.

**Environment**
Node: v7.0.0
yarn : 1.3.2

package.json
```
 "dependencies": {
    "react": "16.2.0",
    "react-native": "0.50.4",
  },
  "resolutions": {
    "react-native/metro-bundler": "0.22.1",
  },
```

![image](https://user-images.githubusercontent.com/24507884/33549859-f384b0a8-d911-11e7-8328-858912f0898c.png)

**Comment by rafeca** [comment]
Thanks for reporting.

Recently (https://github.com/facebook/metro/commit/81bfef03898d366ff0f31792af41e8e99b0176ac) we changed the API to set the modules to be run before the main module in metro.

The change on the default parameters used by react-native (https://github.com/facebook/react-native/commit/503b4521a6ce6bb2282631df616440fa71416d25#diff-75692fe55c8b1a7c05f4264301342167) hasn't hit any stable version of react-native yet (due to the different release cycles of react-native), so this means that if you want to use the latest metro version with the current react-native version you'll have to setup this property manually in your custom config.

**Comment by krishnalelas** [comment]
@rafeca  oh ok. Noted.  
Is there any doc available for custom config.
Thanks.

**Comment by rafeca** [comment]
@krishnalelas I could only find some docs about creating custom configs in https://facebook.github.io/react-native/docs/performance.html (section "Adding a packager config file"). We should definitely make this more visible.
