### ISSUE TITLE
Metro uses watchman that leaks watched files

### ISSUE THREAD

**Issue by assertnotnull** [facebook/metro#1207]
In an new expo project created by "npx create-expo-app --template", when doing "expo start" the metro bundler uses watchman that watches over 100k files. Watching this amount of files takes 1Gb of RAM and Watchman keeps running after stopping expo.
![image](https://github.com/facebook/metro/assets/821567/419a81d6-e73b-440e-b3d4-ca095b7665b0)

**Comment by robhogan** [comment]
Hi, that's as designed - 100k files sounds about right for watching everything in a new project.

Watchman is deliberately persistent, so that tools that use it don't have to re-crawl all files every time they start. When Metro starts, if Watchman is already running, Metro can just quickly query it for changed files. Jest works in the same way, and can "share" Watchman with Metro.

If you prefer not to use Watchman you can turn it off with `resolver.useWatchman: false` in your `metro.config.js`, but note that this will mean increased startup times, especially if you frequently stop and start Expo CLI.

**Comment by robhogan** [comment]
Closing this as I don't think there's a concrete issue here, but feel free to open a follow-up.
