### ISSUE TITLE
Can not import modules with a non-literal specifier

### ISSUE THREAD

**Issue by Shperung** [facebook/metro#1258]
Can not import modules with a non-literal specifier. I think it's the metro case. I try async import with dynamic path react-native and I expect the correct loading module. But I have an error (Invalid call at line 30: import(./theme/${path})])
I'm not sure what it is bug. But I did not find information about impossible import modules with a non-literal specifier

**My version "react-native": "0.72.12",**

There is a simple demo code
```js
export function App() {
  const load = async (path: string) => {
    // I have success - {"test": [Function test]}
    const res = await import('./theme/test');

    // I have error - Invalid call at line 30: import(`./theme/${path}`)]
    const res2 = await import(`./theme/${path}`);
  };

  useEffect(() => {
    load('test');
  }, []);

  return <Text>test</Text>;
}
```

my metro.config.js:

```js
const path = require('path');
const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');

const defaultConfig = getDefaultConfig(__dirname);
const { assetExts, sourceExts } = defaultConfig.resolver;

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */
const config = {
  projectRoot: path.resolve(__dirname, './mobile/'),
  watchFolders: [path.resolve(__dirname, './')],
  transformer: {
    enableBabelRCLookup: false,
    babelTransformerPath: require.resolve('react-native-svg-transformer'),
  },
  resolver: {
    assetExts: assetExts.filter(ext => ext !== 'svg'),
    sourceExts: [...sourceExts, 'svg', 'mjs'],
    resolveRequest: (context, moduleName, platform) => {
      if (moduleName.startsWith('@lingui/message-utils'))
        moduleName = moduleName.replace('@lingui/message-utils/', '@lingui/message-utils/dist/');
      return context.resolveRequest(context, moduleName, platform);
    },
  },
};

module.exports = mergeConfig(defaultConfig, config);
```

**Comment by robhogan** [comment]
Hi @Shperung, this is a known limitation and briefly documented at https://metrobundler.dev/docs/module-api/#require

> The argument to `require()` must be a compile-time constant.

The reason is essentially that Metro's job is to figure out which files to put into the bundle, and we can't do that without being able to resolve imports at build time.

There is a `require.context` experimental API (similar to Webpack's) for including all files matching some pattern, but typically for cases like yours the best solution is to explicitly list all of the possible literal imports and `switch` on whatever variable you want to choose between them.
