### ISSUE TITLE
postProcessModules not working now

### ISSUE THREAD

**Issue by cliberal** [facebook/metro#210]
**Do you want to request a *feature* or report a *bug*?**
probably
**What is the current behavior?**
``` js
// metro.config.js
module.exports = {
  resolver: {
    /* resolver options */
  },
  transformer: {
    /* transformer options */
  },
  serializer: {
    /* serializer options */
    postProcessModules: function(modules, entryFiles) {
      console.log(modules);
      console.log(entryFiles);
    },
  },
  server: {
    /* server options */
  },
};

```
I try to add breakpoint but it doesn't execute the postProcessModules function.

**Comment by rafeca** [comment]
Hi @cliberal ! Thanks for reporting the issue! `postProcessModules` is currently being unused at the moment and we're thinking about deprecating this option (I'm not sure that the API that it exposes is the right one).

Out of curiosity, what are you trying to do with it?

**Comment by cliberal** [comment]
thanks for explanation，I want to skip some common dependencies before generating the final code. 
e.g.
```
postProcessModules: function(modules, entryFiles) {
    return modules.filter(module => !module.path.match(MY_REGEX))
}
```
[https://github.com/facebook/react-native/pull/10804](https://github.com/facebook/react-native/pull/10804)

suppose there‘re several RN applications need to integrate with existing native app. we want to split the common libarary like `react-native`、`polyfills` from the full bundle.  Maybe there's an alternative way I missed it ...

**Comment by rafeca** [comment]
Makes sense! 😀 We're currently working on a new way to customize the output of the bundle. With the new API you are going to be able to write your own serializer which takes the whole dependency graph as an input and returns the bundle as an output (we have all the internals already ready for this, but we are working on a nice API to expose this. As an example, currently [this is the default Metro JS serializer](https://github.com/facebook/metro/blob/master/packages/metro/src/DeltaBundler/Serializers/plainJSBundle.js)).

I'm estimating that we can have this API ready in ~1-2 months, and this is going to allow implementing code splitting quite easily.

In the mean time, code splitting can be done by asking Metro to build the dependency graph and serializing it manually (using the Metro internals). I have [an example of this](https://github.com/rafeca/metro-sample-app/commit/a167bff2b2b6a6fb67efe9b3ed642999a88108db) in my sample app (**disclaimer**: use this on your own, since accessing Metro internals means very probable breakages in the future).

Regarding `postProcessModules`, I don't think that we're going to be able to re-add support for it (we prefer to focus on the mid-term plans rather than working on re-adding an option that is going to disappear soon), but if you are blocked on this I encourage you to send a PR 😃 

Hope that the response helps 😊

**Comment by cliberal** [comment]
Very helpful, thank you for your patience. Looking forward to the new features. I will fork it temporarily, maybe send a PR 😄

**Comment by rafeca** [comment]
Closing this issue, since thanks to your PR now we have the `processModuleFilter` param which replaces the old one

**Comment by cliberal** [comment]
@rafeca 🎉🎉 Thanks for review. Looking forward to the new release
