### ISSUE TITLE
Crash in release mode due to shadowed variables in transpiled code when using Platform.OS checks

### ISSUE THREAD

**Issue by mjmasn** [facebook/metro#238]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Using `Platform.OS` can break the generated code by shadowing variables used by imports. This will crash on iOS and Android in release mode if the check is inside a child class that accesses static properties of its parent class. I guess this isn't really common and we may well change the code but it still appears to be a metro-related bug as it works fine without the `Platform.OS` check.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
https://github.com/mjmasn/PossibleMetroBug

Either look at bundle.js and bundle2.js (as mentioned in README of the linked repo)

or generate new bundles before and after [this commit](https://github.com/mjmasn/PossibleMetroBug/commit/5304d2ec365f04a03a21a96293d1243bae5e01f2)
I used: 

`react-native bundle --platform ios --dev false --minify false --entry-file index.js --bundle-output bundle.js`

**What is the expected behavior?**
The code isn't broken.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**
```
metro@0.38.4
react-native@0.56.0
```
(appears to still be an issue in metro@0.43.6 / react-native@0.57.0-rc.3 though)
```
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 16.04.5 LTS (Xenial Xerus)
      CPU: x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
      Memory: 1.04 GB / 15.54 GB
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 8.11.0 - ~/.nvm/versions/node/v8.11.0/bin/node
      Yarn: 1.9.4 - /usr/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        Build Tools: 23.0.1, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3
        API Levels: 16, 19, 22, 23, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4670197
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

**Comment by rafeca** [comment]
Thanks for reporting! And specially for the awesome repro steps, these are really helpful 😀 

This looks like an issue with babel, since the generated code has variables clashing between each other. We've reported [a few similar issues](https://github.com/babel/babel/issues/created_by/mjesun) to the babel team and it seems like this one may be caused by any of them.

In this specific case, the issue could be caused by the commonjs babel plugin clashing with the metro platform inline plugin, since we used to run them in the same transformation process.

In the latest version of Metro we've changed the way that we apply the babel plugins, so we apply the optimizations in a separate step, so maybe by pure chance we could have worked around this issue. 

Can you check if the issue still reproduces with react native `v0.57.0-rc.4`? (making sure that Metro v0.45.1 is installed)

Thanks!

**Comment by mjmasn** [comment]
Thanks for the reply @rafeca, looks like rc4 was released not long after I submitted this issue - and couldn't get rc3 to play ball with metro 0.45 at the time. I will try to get back to you on that one on Monday

In case anyone else comes across this in the meantime there are various workarounds like:
```
import {Platform} from 'react-native';
import A from './a';

const A2 = A;

class B extends A {
  // if (Platform.OS === ...
  // Use A2 inside the class
}
```

or this (we did this for now because it meant fewer code changes but the downside is the dead code isn't removed):
```
import {Platform as platform} from 'react-native'; 
import A from './a';

class B extends A {
  // if (platform.OS === ... (lowercase p)
  // Use A as normal inside the class
}
```

**Comment by mjmasn** [comment]
@rafeca sorry for the delay, ended up being a busy week...

I've just upgraded our app to RN 0.57 and the problem seems to be resolved. My colleague will confirm release builds for iOS are working next Tuesday but I generated an iOS bundle on my Ubuntu machine and the output code looked good both with and without minification :)
