### ISSUE TITLE
TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by gemery1** [facebook/metro#281]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Code from the [`lodash-compat`](https://github.com/lodash-archive/lodash-compat) library triggers the following error when run with `dev=false`:

```
TypeError: Cannot convert object to primitive value
    at _evaluate (/bug-test/node_modules/@babel/traverse/lib/path/evaluation.js:287:21)
    at evaluateCached (/bug-test/node_modules/@babel/traverse/lib/path/evaluation.js:45:17)
    at NodePath.evaluate (/bug-test/node_modules/@babel/traverse/lib/path/evaluation.js:405:15)
    at evaluate (/bug-test/node_modules/metro/src/JSTransformer/worker/constant-folding-plugin.js:30:30)
    at PluginPass.exit (/bug-test/node_modules/metro/src/JSTransformer/worker/constant-folding-plugin.js:79:22)
    at newFn (/bug-test/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/bug-test/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/bug-test/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/bug-test/node_modules/@babel/traverse/lib/path/context.js:97:8)
```

When run with `dev=true` no error is triggered and the bundling works as expected.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

Run `metro build index.js -O output`, where index.js is as follows:
```
var isHostObject = (function() {
  try {
    Object({ 'toString': 0 } + '');
  } catch(e) {
    return function() { return false; };
  }
  return function(value) {
    // IE < 9 presents many host objects as `Object` objects that can coerce
    // to strings despite having improperly defined `toString` methods.
    return typeof value.toString != 'function' && typeof (value + '') == 'string';
  };
}());

module.exports = isHostObject;
```

**What is the expected behavior?**
No error should be triggered and the bundling should continue.

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**
`metro 0.47.1`
`metro-core 0.47.1`
`node 8.11.1`
`yarn 1.10.1`
`macOS 10.13.6`

**Comment by rafeca** [comment]
Wow thanks for reporting! That's a weird bug 😅I appreciate the specific repro steps.

The problem here is that in order to do dead code elimination, `Metro` uses `path.evaluate()` from Babel to evaluate certain expressions that can be calculated on build time.

In this case, when Babel tries to evaluate `Object({toString: 1232}) + ''`, Nodejs throws the `Cannot convert object to primitive value` error and the exception gets propagated.

What we can do in Metro land is to add a `try/catch` on the call to evaluate (https://github.com/facebook/metro/blob/master/packages/metro/src/JSTransformer/worker/constant-folding-plugin.js#L30) and return `{confident: false, value: null}` in the case that there's an error.

Mind sending a PR for this? You can also create a unit test for this in the `constant-folding-plugin-test.js` file.

Also, may be worth to report this to Babel, since probably Babel shouldn't throw under such circumstances (cc/ @hzoo).

/cc @mjesun

**Comment by gemery1** [comment]
Thanks for the swift response @rafeca. I've opened a [pull request](https://github.com/facebook/metro/pull/283) with the change you recommended and I'm pleased to say it's working on my local machine.

I typically work with native code rather than JavaScript so I hope this gels with the solution you were thinking of. Suggestions are very welcome.

**Comment by rafeca** [comment]
Thanks a lot for submitting the fix! ❤️

I'm currently landing it and it will be available in the next version of Metro (which we'll probably publish next week)
