### ISSUE TITLE
Missing search results as website is not completely indexed by Algolia

### ISSUE THREAD

**Issue by karanjthakkar** [facebook/metro#341]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The website is not completely indexed by Algolia so a lot of important search terms are still unsearchable.

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

Example: 

<img width="1680" alt="screen shot 2019-01-04 at 17 38 39" src="https://user-images.githubusercontent.com/1824298/50702137-f58ea700-1047-11e9-82fb-de7c33d06b60.png">

**What is the expected behavior?**
All config options (atleast) should show up in the search on the website

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**
N/A

I am unsure how to go about fixing this myself since I couldn't find any Algolia related settings in the codebase. Happy to help out if you point me in the right direction 🙂

**Comment by rafeca** [comment]
Thanks for reporting!! 😁

I'm gonna dig since I also don't know how Algolia search was set up (I think @cpojer did it when he created the website)

**Comment by rafeca** [comment]
Ok, looks like algolia is not indexing correctly the text that's inside tables (all the other text in the Configuration page works fine). This is unfortunate since all the config options are inside tables 😅

We can change the layout of the configuration options so they are not in a table but each one is a small section (`h4` or something like that). I've wanted to do that in the past when I wanted to add a more detailed description to some of the options (or a default value).

Is this something you would be willing to do? 😃

**Comment by karanjthakkar** [comment]
@rafeca Do you mean something like https://babeljs.io/docs/en/options? I can try to setup the website locally and see if I can get it working :)

**Comment by rafeca** [comment]
> @rafeca Do you mean something like https://babeljs.io/docs/en/options? I can try to setup the website locally and see if I can get it working :)

Yeah that's exactly what I mean :)
