### ISSUE TITLE
Implement module tree shaking

### ISSUE THREAD

**Issue by chang-ke** [facebook/metro#632]
I'm implementing module level's tree shaking in here https://github.com/chang-ke/metro/pull/1 （it can shake lodash-es,react-native-svg now）hope given some suggestions

**Comment by chang-ke** [comment]
@cpojer

**Comment by cpojer** [comment]
I actually find this super interesting. What status is your PR in? How far along is the implementation and can you show some differences in bundle sizes?

**Comment by chang-ke** [comment]
> I actually find this super interesting. What status is your PR in? How far along is the implementation and can you show some differences in bundle sizes?

actually it used in my project now, but no test case. the differences of bundle sizes dependes on what npm package you used, I will give some cases and this pr has example project that you can get some real differences bundle sizes by running

**Comment by jsamr** [comment]
Just a side note: I propose that tree-shaking for metro bundler follows webpack `sideEffects` package.json field, see https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

**Comment by chang-ke** [comment]
> Just a side note: I propose that tree-shaking for metro bundler follows webpack `sideEffects` package.json field, see https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

got it

**Comment by chang-ke** [comment]
> I actually find this super interesting. What status is your PR in? How far along is the implementation and can you show some differences in bundle sizes?

<details>
  <summary>metro config</summary>

```js
  /**
   * Metro configuration for React Native
   * https://github.com/facebook/react-native
   *
   * @format
   */
  
  const path = require('path');
  
  const { getDefaultConfig } = require('metro-config');
  
  module.exports = (async () => {
    const {
      resolver: { sourceExts, resolverMainFields },
    } = await getDefaultConfig();
    return {
    watchFolders: [path.resolve('../packages/')],
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: false,
        },
      }),
      experimentalTreeShaking: true,
      assetRegistryPath: require.resolve(
        'react-native/Libraries/Image/AssetRegistry',
      ),
      babelTransformerPath: require.resolve('../packages/metro-react-native-babel-transformer'),
    },
    serializer: {
      getPolyfills: require('react-native/rn-get-polyfills'),
      getModulesRunBeforeMainModule: () => [require.resolve(
        require.resolve('react-native/Libraries/Core/InitializeCore'),
      )]
    },
    resolver: {
      sourceExts: ['ios.js', 'android.js', ...sourceExts],
      blockList: /(website\/node_modules\/.*|.*\/__tests__\/.*)$/,
      resolverMainFields: ['react-native', 'module', ...resolverMainFields],
    },
  }})();
```
</details>

## common bundle (only react-native@0.64-rc2)
**index.js:**
```js
/**
 * @format
*/
import {AppRegistry} from 'react-native'
```
### bundle size: 658KB
----
## common bundle with react-native-svg
**index.js:**
```js
/**
 * @format
 */
import {AppRegistry} from 'react-native'
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);
```
**App.js:**
```js

import React from 'react';
import {SafeAreaView, StatusBar, Text} from 'react-native';
import {Svg, Path} from 'react-native-svg';

const App = () => {
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <Svg
          width="130"
          height="130"
          fill="blue"
          stroke="red"
          color="green"
          viewBox="-16 -16 544 544">
          <Path
            d="M318.37,85.45L422.53,190.11,158.89,455,54.79,350.38ZM501.56,60.2L455.11,13.53a45.93,45.93,0,0,0-65.11,0L345.51,58.24,449.66,162.9l51.9-52.15A35.8,35.8,0,0,0,501.56,60.2ZM0.29,497.49a11.88,11.88,0,0,0,14.34,14.17l116.06-28.28L26.59,378.72Z"
            strokeWidth="32"
          />
          <Path d="M0,0L512,512" stroke="currentColor" strokeWidth="32" />
        </Svg>
      </SafeAreaView>
    </>
  );
};

export default App;

```

### no tree-shaking bundle size: 1191KB
### tree-shaking bundle size: 700KB

----
## common bundle with lodash-es
**index.js:**
```js
/**
 * @format
 */
import {AppRegistry} from 'react-native'
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);
```
**App.js:**
```js
import React from 'react';
import {SafeAreaView, StatusBar, Text} from 'react-native';
import {toString} from 'lodash-es';

const App = () => {
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <Text>{toString([1, 2])}</Text>
      </SafeAreaView>
    </>
  );
};

export default App;
```

### no tree-shaking bundle size: 940KB
### tree-shaking bundle size: 661KB

**Comment by wilau2** [comment]
What is the next step here? 

I have to say I am very interested in this work. 

We are now at `7.10 mB` in our project.

@chang-ke could it be useful that we try your fix in our project?

If you can give me the basics on how to use it in my project I could give another example of tree-shaking for our huge app.

**Comment by chang-ke** [comment]
> What is the next step here?
> 
> I have to say I am very interested in this work.
> 
> We are now at `7.10 mB` in our project.
> 
> @chang-ke could it be useful that we try your fix in our project?
> 
> If you can give me the basics on how to use it in my project I could give another example of tree-shaking for our huge app.

you can clone this repo and run it by https://github.com/facebook/metro/issues/632#issuecomment-790253097 's metro config or https://github.com/chang-ke/metro/tree/feature/tree-shaking/examples.

**Comment by hannojg** [comment]
May I ask why this has been closed?

- Has it been merged? 
- Did the metro team decide on not supporting it at all?
- Has there been some official correspondence between the metro team and the rnx-kit team, where the result is, that metro won't take care of it and if devs want tree shaking they should look into rnx-kit?

Thanks in advance for your response!

**Comment by robhogan** [comment]
Hi @hannojg, this issue was closed by the author, no PR to Metro was ever opened. I guess they didn't have time to finish it, but the work (on their fork: https://github.com/chang-ke/metro/pull/1) looked interesting.

Tree shaking isn't a priority within Meta right now but we're open to contributions - as this would be quite a complex feature, it'd be a good idea to open a discussion about approaches first.

**Comment by johnculviner** [comment]
Bump

Wasn't a big reason why Hermes was created was to reduce app start time? Rather than creating an entirely new JavaScript engine using the example above treeshaking would cut 1/3 off the bundle size (and maybe about 1/3 off the start time too without Hermes - not sure if it would change anything WITH Hermes but not sure on that)

I think doing this should be considered. I'm looking at my bundle with `npx react-native-bundle-visualizer` and seeing all sorts of things that really shouldn't be in there.

**Comment by russeg** [comment]
@johnculviner, the contributor said it was not a facebook priority. their needs comes first not the community.

**Comment by iketw** [comment]
@robhogan has FB reconsidered implementing tree-shaking support out of the box?

**Comment by robhogan** [comment]
@iketw we've explored it with interest! Because Metro already only bundles explicitly imported files/modules rather than packages, the gains from tree shaking (=identifying unused imports and eliminating them) are less than some bundlers, and as far as we've seen, not a big win in practice, especially under Hermes where the impact is only on a small fraction of download size vs a binary, with no runtime benefit. It *would* be a bigger win on web, but that hasn't been Metro's focus.

The technical issue here is that very few modules are safely eligible for shaking, because we'd need to be certain they're side-effect free, and only a tiny proportion (of *packages*) claim that they are via `sideEffects`. It's not generally possible to determine that a module is side-effect free statically, because JS is what it is.

We're absolutely open to explorations in this area though - I'd love to be able to say "Metro does tree shaking", but the fact is folks who've experimented with it haven't yet found worthwhile gains.

**Comment by kelset** [comment]
For what's worth, at Microsoft we have made a plugin for Metro to do treeshaking via esbuild ([here](https://github.com/microsoft/rnx-kit/tree/main/packages/metro-serializer-esbuild)) and it had led to good results in our complex real world apps (Office and Xbox to name a couple) for over two years ([link to the first release](https://github.com/microsoft/rnx-kit/blob/main/packages/metro-serializer-esbuild/CHANGELOG.md#001)). We have a whole guide around bundling enhanced by rnx-kit [here](https://microsoft.github.io/rnx-kit/docs/guides/bundling).

**Comment by iketw** [comment]
> For what's worth, at Microsoft we have made a plugin for Metro to do treeshaking via esbuild ([here](https://github.com/microsoft/rnx-kit/tree/main/packages/metro-serializer-esbuild)) and it had led to good results in our complex real world apps (Office and Xbox to name a couple) for over two years ([link to the first release](https://github.com/microsoft/rnx-kit/blob/main/packages/metro-serializer-esbuild/CHANGELOG.md#001)). We have a whole guide around bundling enhanced by rnx-kit [here](https://microsoft.github.io/rnx-kit/docs/guides/bundling).

@kelset thanks for your reply. Based on @robhogan's answer, it seems that the only thing missing for full tree-shaking is unused imports, is that what the MS's plugin completes in the cycle? 

Also, I'm building a RN SDK using native modules and JS code. If I use the plugin in my SDK's metro config, if the hosting app does not include the plugin, will it still tree-shake the dependencies inside my SDK?

**Comment by robhogan** [comment]
(I just corrected the above, I meant to say unused exports rather than imports)

`rnx-kit`'s approach is valid - it moves ESM->CJS transformation from the transform stage to the serialisation stage, which allows the serialiser (esbuild) to safely identify unused exports. It's not exactly how Metro is *designed* to work (expensive, cached transformation, cheap serialisation) but it's fair enough 😅. I'd say the main caveat to watch our for is that it uses a different module system in dev vs prod, which could lead to some subtle issues. But, with Static Hermes ESM support coming, we could do this more consistently and with less serialiser work.

I'd be really curious if you @kelset (or maybe @tido64?) had some real-world numbers to share vs a minifier, and whether the gains were were mostly in 1P or 3P code  - it could help me get this off the ground as a project :).

> Also, I'm building a RN SDK using native modules and JS code. If I use the plugin in my SDK's metro config, if the hosting app does not include the plugin, will it still tree-shake the dependencies inside my SDK?

Unfortunately no, `rnx-kit` would need to be configured by the app developer. As a library developer the best thing you can do is to structure your code in a way that doesn't need so much shaking - use multiple entry files if possible to allow app devs to import only the chunks of your sdk that they need (eg `import featureA from 'sdk/featureA'`), and conversely avoid "barrel files" that export everything.

**Comment by kelset** [comment]
@iketw :
1. what our plugin for Metro does is leveraging esbuild's built-in treeshaker; you can find a more detailed explanation on how it works [in this discussion](https://github.com/microsoft/rnx-kit/discussions/2922#discussioncomment-8153266).
2. because our tool is a plugin for Metro, the treeshaking happens at the Metro bundle step level: which means that it's used when generating the jsbundle consumed by an app. So unless you use Metro to bundle your SDK that you then gets consumed by hosting apps, you won't get any treeshaking. So probably you'd want your hosting apps to add the plugin; to say it in another way, whoever does the bundling needs to add treeshaking.

**Comment by renchap** [comment]
> we've explored it with interest! Because Metro already only bundles explicitly imported files/modules rather than packages, the gains from tree shaking (=identifying unused ~imports~ exports and eliminating them) are less than some bundlers, and as far as we've seen, not a big win in practice

I am late to the discussion, but if you are using an icon library like Font Awesome, with imports like `import { faShareSquare } from "@fortawesome/pro-solid-svg-icons"`, then tree-shaking is a really big win to app size.
