### ISSUE TITLE
Hermes versions in `metro-hermes-compiler` and `react-native` don't match

### ISSUE THREAD

**Issue by mischnic** [facebook/metro#732]
`react-native@0.66.2` is using `hermes-engine@~0.9.0` which uses bytecode version 84.
`metro-hermes-compiler@0.66.2` is using some older version of hermes, with bytecode version 81.

This means that the hermes bundle isn't interopable between these two supposedly compatible packages. Is `metro-hermes-compiler` unmaintained and the intended way to invoke the `hermesc` binary instead?

```
$ ./node_modules/hermes-engine/osx-bin/hermesc -version
LLVM (http://llvm.org/):
  LLVH version 8.0.0svn
  Optimized build

Hermes JavaScript compiler.
  Hermes release version: 0.9.0
  HBC bytecode version: 84
```

```
$ node -p 'require("metro-hermes-compiler")'
{
  align: [Function: align],
  compile: [Function (anonymous)],
  validateBytecodeModule: [Function (anonymous)],
  getFileLength: [Function (anonymous)],
  VERSION: 81
}
```

cc @motiz88 I'm trying to build a Parcel optimizer plugin that wraps `metro-hermes-compiler`.

**Comment by motiz88** [comment]
Hey @mischnic, sorry for the late response.

Metro's support for Hermes bytecode precompilation is experimental, and we haven't fully rolled it out at Meta yet. We also haven't ironed out the versioning story for OSS, so there are no guarantees yet about compatibility. At any rate, this workflow is designed strictly for development: it compiles modules independently, with all bytecode optimisations turned off, and concatenates them in a way that isn't space-optimised (namely it results in a separate string table per module).

The supported way of invoking the Hermes bytecode compiler *for production* is running one of the `hermesc` binaries shipped as part of the `hermes-engine` package (the same package that contains the Hermes VM). This operates on an entire bundle at a time and can produce optimised bytecode.

@kodafb
As another general heads up, the npm version numbers for React Native and Metro have accidentally lined up, but this is mostly a red herring - the dependency is actually mediated through the [`@react-native-community/cli`](https://github.com/facebook/react-native/blob/6c19dc3266b84f47a076b647a1c93b3c3b69d2c5/package.json#L88) package.

**Comment by mischnic** [comment]
Interesting, thanks!

Another benefit of using `hermesc` from `hermes-engine` that is already installed in the project would that the version will always be compatible with the app because it came from the same package instance.

I haven't though about this so far, but is there a reason you want to use bytecode instead of Javascript during development? At least Parcel's current HMR approach wouldn't work with that because it uses `Function("...")` to evaluate the new code.

**Comment by motiz88** [comment]
The premise is that the JS engine must compile the JS to bytecode at some point before it can execute. In development, offloading bytecode compilation from the app to the bundler is attractive because of a number of converging factors:

1. The host machine (the one running the bundler) may be significantly more powerful than the device running the app. This is particularly noticeable when developing apps on Android hardware as opposed to, say, the iOS Simulator.
2. The app running on the device is typically a debug build, so the Hermes compiler embedded in it can be slower than its full potential because of asserts and missed C++ optimisations.
3. The bundler can cache bytecode for modules that haven't changed, so in the incremental case we can mostly avoid running the bytecode compiler altogether.

We're still working on stabilising this and ensuring this is better overall than our current approach of doing [lazy compilation](https://engineering.fb.com/2019/07/12/android/hermes/#:~:text=js%22%2C%0A%20%20enableHermes%3A%20true%0A%5D-,Lazy%20compilation,-Iteration%20speed%20is) on-device, but it is promising in theory.
