### ISSUE TITLE
Metro has encountered an error: Cannot read properties of undefined (reading 'transformFie'): . . .

### ISSUE THREAD

**Issue by nabtron** [facebook/metro#790]
Error while running react-native app on ios.

react-native version: 0.67.3

Metro has encountered an error: Cannot read properties of undefined (reading 'transformFie'): . . .

Tried changing node version to 17, 16.12, 14, etc. but no use.

Please help / guide. Thanks.

![Screenshot 2022-03-13 at 7 42 31 PM](https://user-images.githubusercontent.com/9471128/158065391-3d83c3c5-603e-4393-b073-b2b914056fa1.png)

detailed error:

```
Metro has encountered an error: Cannot read properties of undefined (reading 'transformFile'): node_modules/metro/src/Bundler.js (48:30)

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0

```

**Comment by daihovey** [comment]
Same issue here.

**Comment by cosmosinnovate** [comment]
I am running into the same issues as above.


<img width="494" alt="Screen Shot 2022-03-14 at 1 54 17 PM" src="https://user-images.githubusercontent.com/8810585/158259788-1f5a9ac9-3455-4e3e-9a16-5117cf265f65.png">

**Comment by rh389** [comment]
Could someone who's experiencing this please post: 
 - Output of `yarn list` or `npm list -a`
 - Contents of `metro.config.js`
 - Contents of `babel.config.js`
 
This does look like we're trying to use `Bundler._transformer` before it's set, but although this code lives on the edge (relying on ordering of promise branches) - it _should_ be ok, and I haven't been able to reproduce.

**Comment by nabtron** [comment]
`metro.config.js`
```
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
};

```
`babel.config.js`
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
};
```
npm list -a is huge, with only one possible warning in it:
```
─┬ react-native-permissions@3.3.1
│ ├── UNMET OPTIONAL DEPENDENCY react-native-windows@>=0.62.0
│ ├── react-native@0.67.4 deduped
│ └── react@17.0.2 deduped
```
No other error.

**Comment by rh389** [comment]
Thanks @nabtron 

> npm list -a is huge, with only one possible warning in it

I'm actually more interested in the package versions you have - my working theory is that this might be a transform bug in a recent minor dependency update, causing promise branches to execute out of order. That's partly because a cluster of recent reports against an old Metro version suggests the issue is in a recently released dependency rather than Metro itself.

You could post the output to a gist if you like, or filter down to `babel-`, `@babel` and `metro-` dependencies and post the versions here. Equivalently, uploading your `package-json.lock` would work.

Are you still regularly seeing this issue?

**Comment by nabtron** [comment]
@rh389 

package-lock.json: https://gist.github.com/nabtron/3ab61e930e3ad997deaa54e294c3e154

**Comment by kidtzz** [comment]
This work for me 

`export NODE_OPTIONS=--openssl-legacy-provider`

and i'm not downgrade my node 

my node `17.7.1`

i'm just install same node from `package.json => dependencies => node` on folder project react-native

**Comment by nabtron** [comment]
@kidtzz so issue is with metro or openssl?

**Comment by NaveenSubburaj** [comment]
Still facing this issue. Any update?

**Comment by nabtron** [comment]
@NaveenSubburaj no, i have abandoned react native due to bugs like these & lack of support and planning to move to native or flutter, lets see.

**Comment by alex27riva** [comment]
Hi everyone, I have the same issue

**Comment by itta611** [comment]
Hi!
I solved this issue with downgrading node version. (In my case, v17.4.0 -> v16.13.0)
```
nodebrew install-binary 16.13.0
nodebrew use 16.13.0
npx react-native run-ios
```

**Comment by robhogan** [comment]
Yes, this is down to incompatibility of older versions of Metro with Node 17+. Contrary to the original issue report here, I haven't seen a reproduction for Node <17. The root cause is Node 17 using OpenSSL 3 (https://github.com/nodejs/node/issues/40455), which drops support for MD4 hashing, which we used until #752.

Three options:
 - Update to React Native 0.68 (Metro 0.67) or higher. That includes the Metro fix for Node 17+ compatibility.
 - Use Node 16 or older.
 - Set `NODE_OPTIONS=--openssl-legacy-provider`

**Comment by ez-tech-global** [comment]
> This work for me
> 
> `export NODE_OPTIONS=--openssl-legacy-provider`
> 
> and i'm not downgrade my node
> 
> my node `17.7.1`
> 
> i'm just install same node from `package.json => dependencies => node` on folder project react-native

It works for me too! thanks

**Comment by ChiuMungZitAlexander** [comment]
I solved this by switching to node v16.

**Comment by Leleka14** [comment]
> 

how did that go? 
moving to flutter or native because you cant setup your environment, good luck

**Comment by nabtron** [comment]
@Leleka14 xcode native is going amazing!

Although it's been a year and now i have coded many apps in react-native (abandoned expo), flutter and native, i loved native the most.

**Comment by haveamission** [comment]
> Yes, this is down to incompatibility of older versions of Metro with Node 17+. Contrary to the original issue report here, I haven't seen a reproduction for Node <17. The root cause is Node 17 using OpenSSL 3 ([nodejs/node#40455](https://github.com/nodejs/node/issues/40455)), which drops support for MD4 hashing, which we used until #752.
> 
> Three options:
> 
> * Update to React Native 0.68 (Metro 0.67) or higher. That includes the Metro fix for Node 17+ compatibility.
> * Use Node 16 or older.
> * Set `NODE_OPTIONS=--openssl-legacy-provider`

Still getting the error with React Native 0.71 on Node 18

**Comment by Jamal-ReachFirst** [comment]
Downgraded to node v16.20.1
react-native v0.67.4

Still facing this issue

**Comment by Jamal-ReachFirst** [comment]
Still facing this issue, reopen this

**Comment by akshitdandyan** [comment]
> This work for me
> 
> `export NODE_OPTIONS=--openssl-legacy-provider`
> 
> and i'm not downgrade my node
> 
> my node `17.7.1`
> 
> i'm just install same node from `package.json => dependencies => node` on folder project react-native

This worked for me as well. My node version is 18.16.1

**Comment by Mihai-github** [comment]
+1

**Comment by Dipali711** [comment]
This work for me
1) Downgrade node version to 16.13.0
2) export NODE_OPTIONS=--openssl-legacy-provider  into .npmrc file inside nvm folder.
3) Add this two line in package.json
"start":  "react-scripts --openssl-legacy-provider start",
"build": "react-scripts --openssl-legacy-provider build",

**Comment by yorickshan** [comment]
> This work for me
> 
> `export NODE_OPTIONS=--openssl-legacy-provider`
> 
> and i'm not downgrade my node
> 
> my node `17.7.1`
> 
> i'm just install same node from `package.json => dependencies => node` on folder project react-native

works for me

**Comment by Martyneris** [comment]
Still facing this same issue in 2024 : 

Starting Metro Bundler
TypeError: Cannot read properties of undefined (reading 'reportEvent')

"expo": "~51.0.26"
"react-native": "0.74.5"
"metro": "~0.80.8",
    "metro-resolver": "~0.80.8",
    "metro-config": "~0.80.8",
    "metro-core": "~0.80.8",
    "metro-runtime": "~0.80.8"

**Comment by ParveshPrimotech** [comment]
![Screenshot_1724439096](https://github.com/user-attachments/assets/5c5d3a90-be45-4f24-85ee-fdeb4342c7f7)


How Do I resolve this issue on React-native.

**Comment by robhogan** [comment]
There are multiple possible root causes to this message, which indicates the transformer failed to load.

The cause at the time this issue was opened has been fixed for more than a year, and anyone still seeing this is likely experiencing a different bug for which we'll need details on how to reproduce. There's no way we can help with "+1" type responses. Please do open a new issue, and we can give this a fresh look.

@Martyneris - that's a different message and definitely not the same issue. Feel free to open a new one with a reproduction.

I'm locking this because the original root cause here is fixed, but please don't be discouraged from opening a new issue.
